language: node_js

matrix:
  include:
    - node_js: '0.10'
      env: TEST_SUITE=SHELL
    - node_js: 'stable'
      env: TEST_SUITE=SHELL
    - node_js: 'stable'
      env: TEST_SUITE=LINT
    - node_js: 'stable'
      env: TEST_SUITE=UNIT

install: ./scripts-ci/posix-install.sh

after_install:
  - npm install -g mocha-typescript

script: ./scripts-ci/posix-script.sh