language: node_js
node_js:
- '0.10'
- '4'
- 'stable'

env:
  - TEST_SUITE=SHELL
  - TEST_SUITE=LINT
  - TEST_SUITE=UNIT

matrix:
  include:
    - node_js: '0.10'
      env: TEST_SUITE=SHELL
    - node_js: 'stable'
      env: TEST_SUITE=SHELL
    - node_js: 'stable'
      env: TEST_SUITE=LINT
    - node_js: 'stable'
      env: TEST_SUITE=UNIT
    - node_js: '4'
      env: TEST_SUITE=UNIT

after_install:
  - npm install -g mocha-typescript

script: npm run test:ci